#!/usr/bin/bash
SCRIPTPATH=$(dirname "$(realpath "$0")")
. $SCRIPTPATH/const-paths

pid=$(ps -aux | grep "podtube\.py" | sed 's/^[^\ ]\+\ \+\([0-9]\+\).*/\1/g')
if [[ -n "$pid" ]]; then
  kill $pid
fi
rm -f $DIRD/podtube.pid
rm -f $DIRD/podtube.lck
