#!/usr/bin/bash
SCRIPTPATH=$(dirname "$(realpath "$0")")
. $SCRIPTPATH/const-paths

kill $(ps -aux | grep "podtube\.py" | sed 's/^[^\ ]\+\ \+\([0-9]\+\).*/\1/g')
rm -f $DIRD/podtube.pid
rm -f $DIRD/podtube.lck
